# Generated by Django 6.0.5 on 2026-05-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
    ]
