# Generated by Django 6.0.5 on 2026-05-15 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0002_pet_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='pets/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='adocao.pet')),
            ],
            options={
                'verbose_name': 'Foto do Pet',
                'verbose_name_plural': 'Fotos dos Pets',
                'ordering': ['-data_upload'],
            },
        ),
    ]
