# Generated by Django 6.0.5 on 2026-05-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0003_fotopet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='foto',
        ),
    ]
