# Generated by Django 6.0.5 on 2026-06-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0004_remove_pet_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.CharField(max_length=100),
        ),
    ]
